#############################################################################
# Makefile for building: Stacked.app/Contents/MacOS/Stacked
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  Stacked.pro
# Template: app
# Command: /Users/hoffdamann/Qt/5.7/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile Stacked.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers -I../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../Qt/5.7/clang_64/mkspecs/macx-clang -F/Users/hoffdamann/Qt/5.7/clang_64/lib
QMAKE         = /Users/hoffdamann/Qt/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Stacked1.0.0
DISTDIR = /Users/hoffdamann/CS3505/Stacked/edu-app-the-ccc/.tmp/Stacked1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wl,-rpath,/Users/hoffdamann/Qt/5.7/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/hoffdamann/Qt/5.7/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		view.cpp \
		teachwin.cpp \
		studwin.cpp \
		loginwin.cpp \
		teachreg.cpp \
		studreg.cpp qrc_style.cpp \
		moc_view.cpp \
		moc_teachwin.cpp \
		moc_studwin.cpp \
		moc_loginwin.cpp \
		moc_teachreg.cpp \
		moc_studreg.cpp
OBJECTS       = main.o \
		view.o \
		teachwin.o \
		studwin.o \
		loginwin.o \
		teachreg.o \
		studreg.o \
		qrc_style.o \
		moc_view.o \
		moc_teachwin.o \
		moc_studwin.o \
		moc_loginwin.o \
		moc_teachreg.o \
		moc_studreg.o
DIST          = ../../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		Stacked.pro view.h \
		teachwin.h \
		studwin.h \
		loginwin.h \
		teachreg.h \
		studreg.h main.cpp \
		view.cpp \
		teachwin.cpp \
		studwin.cpp \
		loginwin.cpp \
		teachreg.cpp \
		studreg.cpp
QMAKE_TARGET  = Stacked
DESTDIR       = 
TARGET        = Stacked.app/Contents/MacOS/Stacked


first: all
####### Build rules

$(TARGET): ui_view.h ui_teachwin.h ui_studwin.h ui_loginwin.h ui_teachreg.h ui_studreg.h $(OBJECTS)  
	@test -d Stacked.app/Contents/MacOS/ || mkdir -p Stacked.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Stacked.pro ../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		Stacked.pro \
		style.qrc \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile Stacked.pro
../../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.7/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.7/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.7/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.7/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.7/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf:
../../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.7/clang_64/mkspecs/common/clang.conf:
../../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/5.7/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.7/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.7/clang_64/mkspecs/features/qml_debug.prf:
../../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.7/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.7/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.7/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.7/clang_64/mkspecs/features/uic.prf:
../../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.7/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.7/clang_64/mkspecs/features/lex.prf:
Stacked.pro:
style.qrc:
../../../Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../../Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl:
../../../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile Stacked.pro

qmake_all: FORCE

Stacked.app/Contents/PkgInfo: 
	@test -d Stacked.app/Contents || mkdir -p Stacked.app/Contents
	@$(DEL_FILE) Stacked.app/Contents/PkgInfo
	@echo "APPL????" > Stacked.app/Contents/PkgInfo
Stacked.app/Contents/Resources/empty.lproj: 
	@test -d Stacked.app/Contents/Resources || mkdir -p Stacked.app/Contents/Resources
	@touch Stacked.app/Contents/Resources/empty.lproj
	
Stacked.app/Contents/Info.plist: 
	@test -d Stacked.app/Contents || mkdir -p Stacked.app/Contents
	@$(DEL_FILE) Stacked.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.cdhoffmann.Stacked,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Stacked,g" -e "s,@LIBRARY@,Stacked,g" -e "s,@TYPEINFO@,????,g" ../../../Qt/5.7/clang_64/mkspecs/macx-clang/Info.plist.app >Stacked.app/Contents/Info.plist

all: Makefile \
		Stacked.app/Contents/PkgInfo \
		Stacked.app/Contents/Resources/empty.lproj \
		Stacked.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents style.qrc $(DISTDIR)/
	$(COPY_FILE) --parents view.h teachwin.h studwin.h loginwin.h teachreg.h studreg.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp view.cpp teachwin.cpp studwin.cpp loginwin.cpp teachreg.cpp studreg.cpp $(DISTDIR)/
	$(COPY_FILE) --parents view.ui teachwin.ui studwin.ui loginwin.ui teachreg.ui studreg.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Stacked.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_style.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_style.cpp
qrc_style.cpp: style.qrc \
		../../../Qt/5.7/clang_64/bin/rcc \
		rc/Vsepartoolbar.png \
		rc/close-pressed.png \
		rc/Hmovetoolbar.png \
		rc/up_arrow.png \
		rc/left_arrow_disabled.png \
		rc/close-hover.png \
		rc/checkbox_unchecked.png \
		rc/radio_unchecked_disabled.png \
		rc/radio_checked.png \
		rc/checkbox_checked_disabled.png \
		rc/Hsepartoolbar.png \
		rc/sizegrip.png \
		rc/down_arrow.png \
		rc/stylesheet-branch-more.png \
		rc/radio_unchecked.png \
		rc/branch_closed-on.png \
		rc/checkbox_unchecked_disabled.png \
		rc/branch_open.png \
		rc/left_arrow.png \
		rc/stylesheet-branch-end.png \
		rc/undock.png \
		rc/right_arrow.png \
		rc/checkbox_indeterminate.png \
		rc/checkbox_checked_focus.png \
		rc/stylesheet-vline.png \
		rc/radio_checked_focus.png \
		rc/branch_closed.png \
		rc/right_arrow_disabled.png \
		rc/down_arrow_disabled.png \
		rc/branch_open-on.png \
		rc/radio_unchecked_focus.png \
		rc/Vmovetoolbar.png \
		rc/transparent.png \
		rc/close.png \
		rc/radio_checked_disabled.png \
		rc/checkbox_checked.png \
		rc/up_arrow_disabled.png \
		rc/checkbox_indeterminate_focus.png \
		rc/checkbox_unchecked_focus.png \
		style.qss
	/Users/hoffdamann/Qt/5.7/clang_64/bin/rcc -name style style.qrc -o qrc_style.cpp

compiler_moc_header_make_all: moc_view.cpp moc_teachwin.cpp moc_studwin.cpp moc_loginwin.cpp moc_teachreg.cpp moc_studreg.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_view.cpp moc_teachwin.cpp moc_studwin.cpp moc_loginwin.cpp moc_teachreg.cpp moc_studreg.cpp
moc_view.cpp: ../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		view.h \
		../../../Qt/5.7/clang_64/bin/moc
	/Users/hoffdamann/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/hoffdamann/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/hoffdamann/CS3505/Stacked/edu-app-the-ccc -I/Users/hoffdamann/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/hoffdamann/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/hoffdamann/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/usr/include -I'/System/Library/Frameworks (framework directory)' -I'/Library/Frameworks (framework directory)' -F/Users/hoffdamann/Qt/5.7/clang_64/lib view.h -o moc_view.cpp

moc_teachwin.cpp: ../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		teachwin.h \
		../../../Qt/5.7/clang_64/bin/moc
	/Users/hoffdamann/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/hoffdamann/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/hoffdamann/CS3505/Stacked/edu-app-the-ccc -I/Users/hoffdamann/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/hoffdamann/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/hoffdamann/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/usr/include -I'/System/Library/Frameworks (framework directory)' -I'/Library/Frameworks (framework directory)' -F/Users/hoffdamann/Qt/5.7/clang_64/lib teachwin.h -o moc_teachwin.cpp

moc_studwin.cpp: ../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		view.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		studwin.h \
		../../../Qt/5.7/clang_64/bin/moc
	/Users/hoffdamann/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/hoffdamann/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/hoffdamann/CS3505/Stacked/edu-app-the-ccc -I/Users/hoffdamann/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/hoffdamann/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/hoffdamann/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/usr/include -I'/System/Library/Frameworks (framework directory)' -I'/Library/Frameworks (framework directory)' -F/Users/hoffdamann/Qt/5.7/clang_64/lib studwin.h -o moc_studwin.cpp

moc_loginwin.cpp: ../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		loginwin.h \
		../../../Qt/5.7/clang_64/bin/moc
	/Users/hoffdamann/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/hoffdamann/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/hoffdamann/CS3505/Stacked/edu-app-the-ccc -I/Users/hoffdamann/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/hoffdamann/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/hoffdamann/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/usr/include -I'/System/Library/Frameworks (framework directory)' -I'/Library/Frameworks (framework directory)' -F/Users/hoffdamann/Qt/5.7/clang_64/lib loginwin.h -o moc_loginwin.cpp

moc_teachreg.cpp: ../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		teachreg.h \
		../../../Qt/5.7/clang_64/bin/moc
	/Users/hoffdamann/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/hoffdamann/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/hoffdamann/CS3505/Stacked/edu-app-the-ccc -I/Users/hoffdamann/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/hoffdamann/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/hoffdamann/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/usr/include -I'/System/Library/Frameworks (framework directory)' -I'/Library/Frameworks (framework directory)' -F/Users/hoffdamann/Qt/5.7/clang_64/lib teachreg.h -o moc_teachreg.cpp

moc_studreg.cpp: ../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		studreg.h \
		../../../Qt/5.7/clang_64/bin/moc
	/Users/hoffdamann/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/hoffdamann/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/hoffdamann/CS3505/Stacked/edu-app-the-ccc -I/Users/hoffdamann/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/hoffdamann/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/hoffdamann/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/usr/include -I'/System/Library/Frameworks (framework directory)' -I'/Library/Frameworks (framework directory)' -F/Users/hoffdamann/Qt/5.7/clang_64/lib studreg.h -o moc_studreg.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_view.h ui_teachwin.h ui_studwin.h ui_loginwin.h ui_teachreg.h ui_studreg.h
compiler_uic_clean:
	-$(DEL_FILE) ui_view.h ui_teachwin.h ui_studwin.h ui_loginwin.h ui_teachreg.h ui_studreg.h
ui_view.h: view.ui \
		../../../Qt/5.7/clang_64/bin/uic
	/Users/hoffdamann/Qt/5.7/clang_64/bin/uic view.ui -o ui_view.h

ui_teachwin.h: teachwin.ui \
		../../../Qt/5.7/clang_64/bin/uic
	/Users/hoffdamann/Qt/5.7/clang_64/bin/uic teachwin.ui -o ui_teachwin.h

ui_studwin.h: studwin.ui \
		../../../Qt/5.7/clang_64/bin/uic
	/Users/hoffdamann/Qt/5.7/clang_64/bin/uic studwin.ui -o ui_studwin.h

ui_loginwin.h: loginwin.ui \
		../../../Qt/5.7/clang_64/bin/uic
	/Users/hoffdamann/Qt/5.7/clang_64/bin/uic loginwin.ui -o ui_loginwin.h

ui_teachreg.h: teachreg.ui \
		../../../Qt/5.7/clang_64/bin/uic
	/Users/hoffdamann/Qt/5.7/clang_64/bin/uic teachreg.ui -o ui_teachreg.h

ui_studreg.h: studreg.ui \
		../../../Qt/5.7/clang_64/bin/uic
	/Users/hoffdamann/Qt/5.7/clang_64/bin/uic studreg.ui -o ui_studreg.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp view.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qtextstream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

view.o: view.cpp view.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		loginwin.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		studwin.h \
		teachwin.h \
		studreg.h \
		teachreg.h \
		ui_view.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGridLayout \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o view.o view.cpp

teachwin.o: teachwin.cpp teachwin.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		ui_teachwin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o teachwin.o teachwin.cpp

studwin.o: studwin.cpp studwin.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		view.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_studwin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o studwin.o studwin.cpp

loginwin.o: loginwin.cpp loginwin.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		ui_loginwin.h \
		view.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loginwin.o loginwin.cpp

teachreg.o: teachreg.cpp teachreg.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		ui_teachreg.h \
		view.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o teachreg.o teachreg.cpp

studreg.o: studreg.cpp studreg.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		loginwin.h \
		view.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_studreg.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGridLayout \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o studreg.o studreg.cpp

qrc_style.o: qrc_style.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_style.o qrc_style.cpp

moc_view.o: moc_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_view.o moc_view.cpp

moc_teachwin.o: moc_teachwin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_teachwin.o moc_teachwin.cpp

moc_studwin.o: moc_studwin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_studwin.o moc_studwin.cpp

moc_loginwin.o: moc_loginwin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loginwin.o moc_loginwin.cpp

moc_teachreg.o: moc_teachreg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_teachreg.o moc_teachreg.cpp

moc_studreg.o: moc_studreg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_studreg.o moc_studreg.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

